name: "Auto PR Alerts"

on:
  push:
    branches:
      - main

jobs:
  create-pr-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Use Create Pull Request Alert Action
        uses: surangajayalath/pull-request-slack-notifier-modified@v1.0.4
        with:
          repository: "surangajayalath/pull-request-slack-notifier-modified"
          base-branch: "main"
          head-branch: "feature-branch"
          pr-title: "Automated Pull Request"
          pr-body: "This is an automated pull request for merging feature changes."
          github-token: ${{ secrets.GIT_TOKEN }}
