name: "Auto PR Alerts"

on:
  push:
    branches:
      - development
      - main

jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: surangajayalath/pull-request-slack-notifier-modified@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          PULL_REQUEST_BRANCH: "main"
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Add your Slack webhook URL as a secret



# name: "Auto PR Alerts"

# on:
#   push:
#     branches:
#       - development
#       - main

# jobs:
#   auto-pull-request:
#     name: PullRequestAction
#     runs-on: ubuntu-latest
#     steps:
#       - name: pull-request-action
#         #uses: vsoch/pull-request-action@master
#         uses: surangajayalath/pull-request-slack-notifier-modified@v5
#         env:
#           GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
#           #BRANCH_PREFIX: "update/"
#           PULL_REQUEST_BRANCH: "main"
    
