name: "Auto PR Alerts"

on:
  push:
    branches:
      - development
      - main

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Open PR
        id: open_pr
        uses: rematocorp/open-pull-request-action@v1
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          from-branch: change_this
          to-branch: change_this
          repository-owner: change_this
          repository: change_this
          
      - name: Echo mergeable PR number
        run: echo ${{ steps.open_pr.outputs.pull_number }}
    
